name: Teste Container
on:
  workflow_dispatch:
jobs:
  build-test:
    runs-on: ubuntu-latest
    container: python:3.14.0b1-alpine3.21
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verifica versão do Python
        run: python3 --version
      - name: Instalação curl Alpine
        run: apk add curl
      - name: Executando o curl
        run: curl https://www.google.com